# Generated by Django 5.0.2 on 2024-02-27 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="arrival",
            old_name="ticket_id",
            new_name="attendee",
        ),
        migrations.RemoveField(
            model_name="arrival",
            name="departure",
        ),
    ]
