# Generated by Django 5.0.2 on 2024-02-27 12:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0002_rename_ticket_id_arrival_attendee_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendee",
            name="added",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="attendee",
            name="changed",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
